site_name: Application Manual
site_author: Neosens


theme:
  name: material
  pdf: true
  logo: images/tiresens_bw.png
  favicon: images/tiresens_sq.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand  # This keeps menus expanded
    - navigation.instant  # Improves navigation performance
    #- toc.integrate
    - navigation.path  # 🔹 Shows the full menu hierarchy inside the hamburger menu
    - navigation.indexes  # 🔹 Keeps the menu structure consistent
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

  palette:
    - scheme: default
      primary: custom
      accent: black 
markdown_extensions:
  - toc:
      title: Quick links
  - attr_list
  - admonition

extra_css:
- styles/extra.css


plugins:
  - search
  # - exporter:
  #     formats:
  #       pdf:
  #         enabled: true
  #         stylesheets:
  #           - resources/stylesheets/pdf.scss
  #         covers:
  #           front: resources/templates/covers/front.html.j2
  #         aggregator:
  #           enabled: true
  #           output: NLP_Control_Center_Manual.pdf
  #           covers: limits

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Devices Screen: devices-screen.md
  - Setup Screen:
      - Device: setup-screen/device.md
      - Update: setup-screen/update.md
      - Diagnostics: setup-screen/diagnostics.md
      - Lock with PIN: setup-screen/lockWithPin.md
      - Tap to Read: setup-screen/tapToRead.md
      - App Settings: setup-screen/appSettings.md
  - Vehicle Screen: 
      - Overview: vehicle-screen/vehicle-screen.md
      - Edit Vehicle: vehicle-screen/editVehicle.md
      - Edit Tire: vehicle-screen/editTire.md
      - Rotate Tires: vehicle-screen/rotate.md
      - Airline Sensor Setup: vehicle-screen/airline.md
      - Odometer Setup: vehicle-screen/odometer.md     
  - Monitor Screen: monitor-screen.md
  - In-Cab Display: inCabDisplay.md